# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Human learning
tagline:          'My career as a computer engineer'
url:              http://marhs.me
paginate:         1
baseurl:          /
author:
  name:           Marco Herrero
  url:            https://marhs.de
  email:          me@marhs.de

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


pages_list:
    About: '/about'
    Archive: '/archive'
