# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Marco Herrero
tagline:             'Data journal'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             'http://marhs.github.io/'
paginate:            5

# About/contact
author:
  name:              Marco Herrero
  url:               https://marhs.de/
  email:             me@marhs.de

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
